//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor.
// WindowApp_res.rc

#define IDD_ABOUT                           100

#define IDI_MAIN                            100

#define IDR_MAINMENU                        100

#define IDS_FAILREGCLASS                    100
#define IDS_TITLE                           101
#define IDS_FAILCREATEWND                   102
#define IDS_APPNAME                         103

#define ID_EXIT                             100
#define ID_ABOUT                            101
#define ID_TEST                             102

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    101
        #define _APS_NEXT_COMMAND_VALUE     103
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
