//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor.
// RichTextFileApp_res.rc

#define IDB_SMALLTOOLBAR                    100
#define IDB_LARGETOOLBAR                    101
#define IDB_SMALLTOOLBAR2                   102
#define IDB_LARGETOOLBAR2                   103

#define IDD_ABOUT                           100

#define IDI_MAIN                            100

#define IDR_MAINMENU                        100
#define IDR_ACCEL                           101

#define IDS_APPNAME                         100
#define IDS_TITLE                           101
#define IDS_FAILREGCLASS                    102
#define IDS_FAILCREATEWND                   103
#define IDS_OPEN                            104
#define IDS_SAVEAS                          105
#define IDS_WANNASAVE                       106
#define IDS_READERROR                       107
#define IDS_WRITEERROR                      108
#define IDS_READY                           109
#define IDS_BUSY                            110
#define IDS_FILTER                          111
#define IDS_NONE                            112
#define IDS_TOOL_NEW                        113
#define IDS_TOOL_OPEN                       114
#define IDS_TOOL_SAVE                       115
#define IDS_TOOL_UNDO                       116
#define IDS_TOOL_REDO                       117
#define IDS_TOOL_CUT                        118
#define IDS_TOOL_COPY                       119
#define IDS_TOOL_PASTE                      120
#define IDS_TOOL_DELETE                     121
#define IDS_TOOL_PRINTPREVIEW               122
#define IDS_TOOL_PRINT                      123
#define IDS_TOOL_PROPERTIES                 124
#define IDS_TOOL_FIND                       125
#define IDS_TOOL_REPLACE                    126
#define IDS_TOOL_HELP                       127
#define IDS_TOOL_SELECTALL                  128
#define IDS_TOOL_PAGESETUP                  129
#define IDS_TOOL_SAVEAS                     130
#define IDS_TOOL_STATUSBAR                  131
#define IDS_TOOL_TOOLBAR                    132
#define IDS_TOOL_RECENT                     133
#define IDS_TOOL_EXIT                       134
#define IDS_TOOL_ABOUT                      135

#define ID_EXIT                             100
#define ID_ABOUT                            101
#define ID_TEST                             102
#define ID_NEW                              103
#define ID_OPEN                             104
#define ID_SAVE                             105
#define ID_SAVEAS                           106
#define ID_STATUSBAR                        107
#define ID_TOOLBAR                          108
#define ID_UNDO                             109
#define ID_REDO                             110
#define ID_CUT                              111
#define ID_COPY                             112
#define ID_PASTE                            113
#define ID_DELETE                           114
#define ID_PRINTPREVIEW                     115
#define ID_PRINT                            116
#define ID_PROPERTIES                       117
#define ID_FIND                             118
#define ID_REPLACE                          119
#define ID_HELP                             120
#define ID_SELECTALL                        121
#define ID_PAGESETUP                        122
#define ID_RECENT_01                        201
#define ID_RECENT_02                        202
#define ID_RECENT_03                        203
#define ID_RECENT_04                        204
#define ID_RECENT_05                        205
#define ID_RECENT_06                        206
#define ID_RECENT_07                        207
#define ID_RECENT_08                        208
#define ID_RECENT_09                        209
#define ID_RECENT_10                        210
#define ID_RECENT_11                        211
#define ID_RECENT_12                        212
#define ID_RECENT_13                        213
#define ID_RECENT_14                        214
#define ID_RECENT_15                        215
#define ID_RECENT_16                        216
#define ID_RECENT_17                        217
#define ID_RECENT_18                        218
#define ID_RECENT_19                        219
#define ID_RECENT_20                        220

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    102
        #define _APS_NEXT_COMMAND_VALUE     221
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
