#pragma once

//#define DX_USE_LOG_FILE

#define DX_COMPANY_NAME_IN_ENGLISH TEXT("Katayama Hirofumi MZ")

//#define DX_HELPFILE TEXT("README.TXT")
//#define DX_HELPFILE TEXT("README.HTM")

#define DX_HELPFILE_DOTEXT TEXT(".TXT")

#define DX_MAX_TEXTCONV_BUFF MAX_PATH
